### ISSUE TITLE
File names for 8.7 and 9.1 installation docs

### ISSUE THREAD

**Issue by wsoyinka** [rocky-linux/documentation#1088] opened 2023-03-07 16:08 UTC
We should probably update the "file names" of install docs from 8.6 and 9.0  to -->  8.7 and 9.1 version respectively.  Ditto all corresponding translated files and .pages.

@sspencerwire thoughts ?

**Comment by NezSez** [comment] 2023-04-17 21:14
Isn't how we do this related to #1044 ? From what I've read so far, which isn't much, the mike plugin requires the use of <major>.<minor> directories right?

**Comment by sspencerwire** [comment] 2023-06-16 12:50
@wsoyinka the problem is the translations:
```
8_6_installation.fr.md
8_6_installation.it.md
8_6_installation.ja.md
8_6_installation.md
8_6_installation.sv.md
8_6_installation.zh.md
```
The 9.x documents suffer none of this, as they are simply named "installation.md" I can rename the source document for 8.x to 8_8_installation.md or simply 8_installation.md, which will hold true until 8 is EOLed. What do you think?  The translations will still be an issue and will probably look like they haven't been completed at all.

**Comment by sspencerwire** [comment] 2023-09-25 13:26
> @wsoyinka the problem is the translations:
> 
> ```
> 8_6_installation.fr.md
> 8_6_installation.it.md
> 8_6_installation.ja.md
> 8_6_installation.md
> 8_6_installation.sv.md
> 8_6_installation.zh.md
> ```
> 
> The 9.x documents suffer none of this, as they are simply named "installation.md" I can rename the source document for 8.x to 8_8_installation.md or simply 8_installation.md, which will hold true until 8 is EOLed. What do you think? The translations will still be an issue and will probably look like they haven't been completed at all.

@wsoyinka I responded to this back in June... Do you want to go ahead with this, or should we close the issue?

**Comment by sspencerwire** [comment] 2024-02-01 17:45
@all-contributors add @ShyRain for content

**Comment by wsoyinka** [comment] 2024-04-19 14:52
Fine with this @sspencerwire .  Thank you :-)

**Closed** 2024-04-20 18:39 UTC
